apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: felipegodoi/todo-list-user-service
    context: ./user-service
    sync:
      manual:
      - src: "user-service/src/**/*.js"
        dest: /app/src
  - image: felipegodoi/todo-list-task-service
    context: ./task-service
    sync:
      manual:
      - src: "task-service/src/**/*.js"
        dest: /app/src
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
