apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: felipegodoi/split-expenses-user-service
    context: ./user-service
    sync:
      manual:
      - src: "user-service/src/**/*.js"
        dest: /app/src
  - image: felipegodoi/split-expenses-group-service
    context: ./group-service
    sync:
      manual:
      - src: "group-service/src/**/*.js"
        dest: /app/src
  - image: felipegodoi/split-expenses-expense-service
    context: ./expense-service
    sync:
      manual:
      - src: "expense-service/src/**/*.js"
        dest: /app/src
  - image: felipegodoi/split-expenses-division-service
    context: ./division-service
    sync:
      manual:
      - src: "division-service/src/**/*.js"
        dest: /app/src
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
